spring.datasource.url=jdbc:mysql://localhost:3306/ordering_retail_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=8081